// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package store

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Booking struct {
	BookingID    uuid.UUID     `json:"booking_id"`
	RoomID       uuid.NullUUID `json:"room_id"`
	CheckInDate  time.Time     `json:"check_in_date"`
	CheckOutDate time.Time     `json:"check_out_date"`
	TotalPrice   string        `json:"total_price"`
	Status       string        `json:"status"`
}

type Guest struct {
	GuestID   uuid.UUID      `json:"guest_id"`
	FirstName string         `json:"first_name"`
	LastName  string         `json:"last_name"`
	Age       int32          `json:"age"`
	Phone     sql.NullString `json:"phone"`
}

type Hotel struct {
	HotelID uuid.UUID `json:"hotel_id"`
	Name    string    `json:"name"`
	Address string    `json:"address"`
}

type Room struct {
	RoomID        uuid.UUID     `json:"room_id"`
	HotelID       uuid.NullUUID `json:"hotel_id"`
	RoomNumber    string        `json:"room_number"`
	Type          string        `json:"type"`
	PricePerNight string        `json:"price_per_night"`
	IsAvailable   sql.NullBool  `json:"is_available"`
}
