// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package store

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Booking struct {
	BookingID    uuid.UUID     `json:"booking_id"`
	RoomID       uuid.NullUUID `json:"room_id"`
	CheckInDate  time.Time     `json:"check_in_date"`
	CheckOutDate time.Time     `json:"check_out_date"`
	TotalPrice   string        `json:"total_price"`
	Status       string        `json:"status"`
}

type BookingGuest struct {
	BookingGuestID uuid.UUID     `json:"booking_guest_id"`
	BookingID      uuid.NullUUID `json:"booking_id"`
	GuestID        uuid.NullUUID `json:"guest_id"`
}

type Guest struct {
	GuestID   uuid.UUID      `json:"guest_id"`
	FirstName string         `json:"first_name"`
	LastName  string         `json:"last_name"`
	Age       int32          `json:"age"`
	Phone     sql.NullString `json:"phone"`
}

type Hotel struct {
	HotelID uuid.UUID `json:"hotel_id"`
	Name    string    `json:"name"`
	Address string    `json:"address"`
}

type Notification struct {
	NotificationID uuid.UUID `json:"notification_id"`
	Message        string    `json:"message"`
	Roles          []string  `json:"roles"`
	IsActive       bool      `json:"is_active"`
}

type Room struct {
	RoomID        uuid.UUID     `json:"room_id"`
	HotelID       uuid.NullUUID `json:"hotel_id"`
	RoomNumber    int32         `json:"room_number"`
	Type          string        `json:"type"`
	PricePerNight string        `json:"price_per_night"`
	IsAvailable   sql.NullBool  `json:"is_available"`
}

type Session struct {
	SessionID uuid.UUID `json:"session_id"`
	UserID    uuid.UUID `json:"user_id"`
	ExpiresAt time.Time `json:"expires_at"`
	IsActive  bool      `json:"is_active"`
}

type User struct {
	UserID    uuid.UUID `json:"user_id"`
	FirstName string    `json:"first_name"`
	LastName  string    `json:"last_name"`
	Email     string    `json:"email"`
	Password  []byte    `json:"password"`
	Role      string    `json:"role"`
	CreatedAt time.Time `json:"created_at"`
}

type UserNotification struct {
	UserID         uuid.UUID    `json:"user_id"`
	NotificationID uuid.UUID    `json:"notification_id"`
	ReadAt         sql.NullTime `json:"read_at"`
}
