// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: sessions.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (session_id, user_id, expires_at)
VALUES ($1, $2, $3)
RETURNING session_id
`

type CreateSessionParams struct {
	SessionID uuid.UUID `json:"session_id"`
	UserID    uuid.UUID `json:"user_id"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, createSession, arg.SessionID, arg.UserID, arg.ExpiresAt)
	var session_id uuid.UUID
	err := row.Scan(&session_id)
	return session_id, err
}

const getSessionById = `-- name: GetSessionById :one
SELECT session_id, user_id, expires_at FROM sessions WHERE session_id = $1
`

func (q *Queries) GetSessionById(ctx context.Context, sessionID uuid.UUID) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionById, sessionID)
	var i Session
	err := row.Scan(&i.SessionID, &i.UserID, &i.ExpiresAt)
	return i, err
}

const getSessionByUserId = `-- name: GetSessionByUserId :one
SELECT session_id, user_id, expires_at FROM sessions WHERE user_id = $1
`

func (q *Queries) GetSessionByUserId(ctx context.Context, userID uuid.UUID) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionByUserId, userID)
	var i Session
	err := row.Scan(&i.SessionID, &i.UserID, &i.ExpiresAt)
	return i, err
}

const updateSession = `-- name: UpdateSession :one
UPDATE sessions
SET expires_at = $2
WHERE session_id = $1
RETURNING session_id
`

type UpdateSessionParams struct {
	SessionID uuid.UUID `json:"session_id"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) UpdateSession(ctx context.Context, arg UpdateSessionParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, updateSession, arg.SessionID, arg.ExpiresAt)
	var session_id uuid.UUID
	err := row.Scan(&session_id)
	return session_id, err
}
